### PR TITLE
WIP: Docker image for Jupyter Notebook

### PR DESCRIPTION
**Pull request by GittiHab**
This repository might not be the correct place for Jupyter Notebooks and I would propose moving them to the graph-exploration repository. To keep the progress though the script is in this repo right now.

This pull request adds a new Docker Image for using Jupyter Notebooks with our dependencies. Currently, this is based on Jupyters own Docker Images –  the problem with that is that they use `conda` as their package manager and all `apt-get` dependencies need to be transferred respectively. A description is yet missing.

The usage would be to copy the notebooks and files into the container using `docker cp`, e.g.:

    docker cp notebooks/. notebook-container:/home/jovyan/

Note that on macOS High Sierra there might be issues with permissions therefore you need to change the permissions of the files manually (untested):

    docker exec -u root notebook-container chown -R jovyan:users .

To get the link to the notebook browser run

    docker exec notebook-container jupyter notebook list

### CODE REVIEW

**Comment by Baschdl** [comment]
Why don't we base our notebook-image on the deployment-image? With this we wouldn't need to maintain the python and Ubuntu package dependencies in two different places.

**Comment by GittiHab** [comment]
Because, as said, I had trouble with that yesterday so instead of starting from scratch I tried building on top of this. I hoped that I could then also include the other image but that didn't work because of the conda environment – I didn't see that coming.

So the options now are: 1. Try create a new image based on our own Dockerfile so that we can more easily maintain the dependencies, 2. decide that we don't need the exact same environment when working with Jupyter as this is only for "research/experimental" purpose and leave it like this for now and invest the time in something else.

I personally wouldn't want to do option 1 as this already cost me two days now.

**Comment by Baschdl** [comment]
I think i'm not completely understanding the problem. Why can't we just install jupyter with `RUN pip3 install jupyter` on top of our other Docker image?.

**Comment by GittiHab** [comment]
> I think i'm not completely understanding the problem. Why can't we just install jupyter with RUN pip3 install jupyter on top of our other Docker image?

Because I can't get it to work for me like this. If you know how than feel free to create such an image.

**Comment by Baschdl** [comment]
Ok, I'll try it. What's the problem in your case?

**Comment by Baschdl** [comment]
Cherry-picked reusable code in #51

**Pull request closed without merging**
