### PR TITLE
Add script to automatically copy new files to container

### PR DESCRIPTION
**Pull request by GittiHab**
This script copies the new source files into the container and installs the new dependencies. This should prevent the need to rebuild the container every time – which can take very long if the internet connection is slow.

### CODE REVIEW

**Comment by Baschdl** [comment]
I think uninstalling the old packages is not necessary because it just makes the script slower. Deleting all old files would yield always a "clean" state in the container but then we need volumes for our notebook and rated_datasets folders (which we need anyways). I would rename the script to something which makes clear that the files are copied into the container and not to some distant server.

**Comment by Baschdl** [comment]
@GittiHab Do you agree? Then we can remove the comments and the WIP label

**Comment by GittiHab** [comment]
I agree, it would be more sensible to use a volume then – but that's another issue.

**Comment by Baschdl** [comment]
Created #54  for this

**Comment by GittiHab** [comment]
Closes #20

**Pull request merged**
